language: python
python:
  - "2.7"
  - "3.4"
env:
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
# branches:
#   only:
#     - master
#     - develop
# command to install dependencies
install:
  - "pip install -q -e ."
  - "pip install -q -r requirements.txt"
  - pip install "$DJANGO"
  - pip install python-coveralls
  - pip install coverage

# command to run tests
script: "coverage run manage.py test"

after_success:
- coveralls